name: Update letme documentation
on:
  pull_request:
    types:
      - closed
    branches:
      - main

env:
  AWS_REGION: eu-west-1
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  id-token: write
  contents: read
  pull-requests: write


jobs:
  deploy:
    if: ${{ github.event_name == 'merge'}}
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.A5T_ID }}:role/github@letme-documentation
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npm run build
      - name: Upload Content
        run: aws s3 sync build/ s3://www.getletme.com/build
      - name: Get distributionId
        run: echo "distributionId=$(aws cloudfront list-distributions | jq -r '.DistributionList.Items[] | select(.Aliases.Items[] == "getletme.com") | .Id')" >> $GITHUB_ENV
      - name: Invalidate cache
        run: aws cloudfront create-invalidation --distribution-id $distributionId --path "/*" > /dev/null 2>&1